---

- name: Install Dependencies (Debian)
  import_tasks: install-debian.yml
  tags:
    - install
  when:
    - ansible_os_family == "Debian"

- name: Ensure install path exists
  file:
    path: '{{ ble_monitor_install_path }}'
    state: directory
    owner: root
    group: root
    mode: 0644
  tags:
    - install

- name: Retrive Monitor.sh repo
  git:
    repo: 'https://www.github.com/andrewjfreyer/monitor.git'
    dest: '{{ ble_monitor_install_path }}'
    version: '{{ monitor_version }}'
  register: monitor_repo
  tags:
    - install

- name: Perform first run of Monitor
  shell:
    cmd: bash monitor.sh
    chdir: '{{ ble_monitor_install_path }}'
  args:
    warn: fale
  failed_when: False
  when:
    - monitor_repo is changed
  tags:
    - install